/* 운동 그림 목록 — id 별로 media/{id}-1.{t} … -{n}.{t} 가 있습니다.

   90개는 Workout Guide(Bryl Lim)의 해부학 일러스트로, 원본은 Everkinetic
   입니다. 둘 다 CC BY-SA 4.0 이라 상업적으로 써도 되지만 출처를 밝혀야
   하고, 그림을 고쳐 쓰면 고친 것도 같은 라이선스로 공개해야 합니다.
   그래서 색이나 형태를 건드리지 않고 원본 그대로 씁니다 (width/height
   속성만 제거해 화면 크기에 맞게 늘어나도록 했습니다). 출처 표기는
   설정 화면 맨 아래에 있습니다.

   한 운동에 3장이 들어오는 것이 이 자료의 핵심입니다. 사진 두 장을
   교차시키던 예전 방식은 '다른 사진으로 바뀌었다'로 읽혔지만, 같은 사람이
   같은 자세에서 이어지는 3장은 실제로 움직이는 것으로 읽힙니다.

   나머지 8개는 카탈로그에 같은 동작이 없어서 예전 것을 그대로 둡니다
   (교정 스트레칭 6개는 직접 그린 그림, 2개는 퍼블릭 도메인 사진).

   t: 파일 확장자   n: 프레임 수 (1이면 가만히 있는 자세) */
const EXERCISE_MEDIA = {
  "ab-wheel": { t: "svg", n: 3 },
  "abduction": { t: "svg", n: 3 },
  "arnold-press": { t: "svg", n: 3 },
  "back-extension": { t: "svg", n: 3 },
  "barbell-curl": { t: "svg", n: 3 },
  "barbell-row": { t: "svg", n: 3 },
  "bench-press": { t: "svg", n: 3 },
  "bicycle-crunch": { t: "svg", n: 3 },
  "bulgarian-split-squat": { t: "svg", n: 3 },
  "cable-crossover": { t: "svg", n: 3 },
  "cable-crunch": { t: "svg", n: 3 },
  "cable-curl": { t: "svg", n: 3 },
  "cable-lateral-raise": { t: "svg", n: 3 },
  "cable-row": { t: "svg", n: 3 },
  "calf-raise": { t: "svg", n: 3 },
  "chin-up": { t: "svg", n: 3 },
  "close-grip-bench": { t: "svg", n: 3 },
  "concentration-curl": { t: "svg", n: 3 },
  "crunch": { t: "svg", n: 3 },
  "db-bench-press": { t: "svg", n: 3 },
  "db-curl": { t: "svg", n: 3 },
  "db-incline-press": { t: "svg", n: 3 },
  "db-shoulder-press": { t: "svg", n: 3 },
  "dead-bug": { t: "svg", n: 3 },
  "deadlift": { t: "svg", n: 3 },
  "decline-press": { t: "svg", n: 3 },
  "dips": { t: "svg", n: 3 },
  "dips-triceps": { t: "svg", n: 3 },
  "dumbbell-fly": { t: "svg", n: 3 },
  "face-pull": { t: "svg", n: 3 },
  "front-raise": { t: "svg", n: 3 },
  "front-squat": { t: "svg", n: 3 },
  "glute-bridge": { t: "svg", n: 3 },
  "goblet-squat": { t: "svg", n: 3 },
  "good-morning": { t: "svg", n: 3 },
  "hack-squat": { t: "svg", n: 3 },
  "hammer-curl": { t: "svg", n: 3 },
  "hanging-leg-raise": { t: "svg", n: 3 },
  "hip-thrust": { t: "svg", n: 3 },
  "hollow-hold": { t: "svg", n: 3 },
  "incline-cable-fly": { t: "svg", n: 3 },
  "incline-db-curl": { t: "svg", n: 3 },
  "incline-press": { t: "svg", n: 3 },
  "kickback": { t: "svg", n: 3 },
  "landmine-press": { t: "svg", n: 3 },
  "lat-pulldown": { t: "svg", n: 3 },
  "lateral-raise": { t: "svg", n: 3 },
  "leg-curl": { t: "svg", n: 3 },
  "leg-extension": { t: "svg", n: 3 },
  "leg-press": { t: "svg", n: 3 },
  "leg-raise": { t: "svg", n: 3 },
  "lunge": { t: "svg", n: 3 },
  "machine-chest-press": { t: "svg", n: 3 },
  "machine-shoulder-press": { t: "svg", n: 3 },
  "mountain-climber": { t: "svg", n: 3 },
  "ohp": { t: "svg", n: 3 },
  "one-arm-db-row": { t: "svg", n: 3 },
  "overhead-tricep-ext": { t: "svg", n: 3 },
  "pec-deck": { t: "svg", n: 3 },
  "pike-push-up": { t: "svg", n: 3 },
  "plank": { t: "svg", n: 3 },
  "preacher-curl": { t: "svg", n: 3 },
  "pull-up": { t: "svg", n: 3 },
  "push-up": { t: "svg", n: 3 },
  "rdl": { t: "svg", n: 3 },
  "rear-delt-fly": { t: "svg", n: 3 },
  "reverse-curl": { t: "svg", n: 3 },
  "reverse-pec-deck": { t: "svg", n: 3 },
  "rope-pushdown": { t: "svg", n: 3 },
  "russian-twist": { t: "svg", n: 3 },
  "seated-calf-raise": { t: "svg", n: 3 },
  "seated-leg-curl": { t: "svg", n: 3 },
  "seated-row": { t: "svg", n: 3 },
  "shrug": { t: "svg", n: 3 },
  "side-plank": { t: "svg", n: 3 },
  "skull-crusher": { t: "svg", n: 3 },
  "squat": { t: "svg", n: 3 },
  "st-child-pose": { t: "svg", n: 3 },
  "st-chin-tuck": { t: "svg", n: 2 },
  "st-couch": { t: "svg", n: 1 },
  "st-dead-bug-post": { t: "svg", n: 3 },
  "st-doorway-pec": { t: "svg", n: 3 },
  "st-glute-bridge": { t: "svg", n: 3 },
  "st-hamstring": { t: "svg", n: 3 },
  "st-kneeling-hipflexor": { t: "svg", n: 3 },
  "st-levator": { t: "svg", n: 1 },
  "st-pec-minor": { t: "svg", n: 1 },
  "st-thoracic-ext": { t: "svg", n: 1 },
  "st-upper-trap": { t: "webp", n: 2 },
  "st-wall-angel": { t: "svg", n: 2 },
  "stiff-leg-deadlift": { t: "svg", n: 3 },
  "straight-arm-pulldown": { t: "svg", n: 3 },
  "svend-press": { t: "webp", n: 2 },
  "t-bar-row": { t: "svg", n: 3 },
  "tricep-pushdown": { t: "svg", n: 3 },
  "upright-row": { t: "svg", n: 3 },
  "woodchopper": { t: "svg", n: 3 },
  "wrist-curl": { t: "svg", n: 3 },
};
