/* 운동 그림 목록 — id 별로 media/{id}-a.{t}, 두 장짜리는 -b 도 함께 있습니다.

   t: 'webp'  실제 사진. 출처는 free-exercise-db (Unlicense · 퍼블릭 도메인)
              으로, 상업 이용과 재배포에 아무 제약이 없습니다.
   t: 'svg'   무료 사진에 같은 동작이 없어서 직접 그린 자세 그림입니다.
              스트레칭·교정 운동은 어느 무료 DB에도 거의 없습니다.
   n: 2       시작 자세와 마친 자세 두 장 — 번갈아 보여 줍니다.
   n: 1       버티는 자세라 한 장으로 충분한 운동.

   동작이 다른 그림을 억지로 붙이면 잘못된 자세를 가르치게 되므로, 정확히
   같은 동작을 찾지도 그리지도 못한 운동은 일부러 비워 두었습니다. 목록에
   없는 운동은 정보창에서 그림 영역이 통째로 빠집니다. */
const EXERCISE_MEDIA = {
  "ab-wheel": { t: "webp", n: 2 },
  "abduction": { t: "webp", n: 2 },
  "arnold-press": { t: "webp", n: 2 },
  "back-extension": { t: "webp", n: 2 },
  "barbell-curl": { t: "webp", n: 2 },
  "barbell-row": { t: "webp", n: 2 },
  "bench-press": { t: "webp", n: 2 },
  "bicycle-crunch": { t: "webp", n: 1 },
  "bulgarian-split-squat": { t: "webp", n: 2 },
  "cable-crossover": { t: "webp", n: 2 },
  "cable-crunch": { t: "webp", n: 2 },
  "cable-curl": { t: "webp", n: 2 },
  "cable-lateral-raise": { t: "webp", n: 2 },
  "cable-row": { t: "webp", n: 2 },
  "calf-raise": { t: "webp", n: 2 },
  "chin-up": { t: "webp", n: 2 },
  "close-grip-bench": { t: "webp", n: 2 },
  "concentration-curl": { t: "webp", n: 2 },
  "crunch": { t: "webp", n: 2 },
  "db-bench-press": { t: "webp", n: 2 },
  "db-curl": { t: "webp", n: 2 },
  "db-incline-press": { t: "webp", n: 2 },
  "db-shoulder-press": { t: "webp", n: 2 },
  "dead-bug": { t: "webp", n: 2 },
  "deadlift": { t: "webp", n: 2 },
  "decline-press": { t: "webp", n: 2 },
  "dips": { t: "webp", n: 2 },
  "dips-triceps": { t: "webp", n: 2 },
  "dumbbell-fly": { t: "webp", n: 2 },
  "face-pull": { t: "webp", n: 2 },
  "front-raise": { t: "webp", n: 2 },
  "front-squat": { t: "webp", n: 2 },
  "glute-bridge": { t: "webp", n: 2 },
  "goblet-squat": { t: "webp", n: 2 },
  "good-morning": { t: "webp", n: 2 },
  "hack-squat": { t: "webp", n: 2 },
  "hammer-curl": { t: "webp", n: 2 },
  "hanging-leg-raise": { t: "webp", n: 2 },
  "hip-thrust": { t: "webp", n: 2 },
  "hollow-hold": { t: "svg", n: 1 },
  "incline-cable-fly": { t: "webp", n: 2 },
  "incline-db-curl": { t: "webp", n: 2 },
  "incline-press": { t: "webp", n: 2 },
  "kickback": { t: "webp", n: 2 },
  "landmine-press": { t: "webp", n: 2 },
  "lat-pulldown": { t: "webp", n: 2 },
  "lateral-raise": { t: "webp", n: 2 },
  "leg-curl": { t: "webp", n: 2 },
  "leg-extension": { t: "webp", n: 2 },
  "leg-press": { t: "webp", n: 2 },
  "leg-raise": { t: "webp", n: 2 },
  "lunge": { t: "webp", n: 2 },
  "machine-chest-press": { t: "webp", n: 2 },
  "machine-shoulder-press": { t: "webp", n: 2 },
  "mountain-climber": { t: "webp", n: 2 },
  "ohp": { t: "webp", n: 2 },
  "one-arm-db-row": { t: "webp", n: 2 },
  "overhead-tricep-ext": { t: "webp", n: 2 },
  "pec-deck": { t: "webp", n: 2 },
  "pike-push-up": { t: "svg", n: 2 },
  "plank": { t: "webp", n: 2 },
  "preacher-curl": { t: "webp", n: 2 },
  "pull-up": { t: "webp", n: 2 },
  "push-up": { t: "webp", n: 2 },
  "rdl": { t: "webp", n: 2 },
  "rear-delt-fly": { t: "webp", n: 2 },
  "reverse-curl": { t: "webp", n: 2 },
  "reverse-pec-deck": { t: "webp", n: 2 },
  "rope-pushdown": { t: "webp", n: 2 },
  "russian-twist": { t: "webp", n: 2 },
  "seated-calf-raise": { t: "webp", n: 2 },
  "seated-leg-curl": { t: "webp", n: 2 },
  "seated-row": { t: "webp", n: 2 },
  "shrug": { t: "webp", n: 2 },
  "side-plank": { t: "webp", n: 2 },
  "skull-crusher": { t: "webp", n: 2 },
  "squat": { t: "webp", n: 2 },
  "st-child-pose": { t: "webp", n: 2 },
  "st-chin-tuck": { t: "svg", n: 2 },
  "st-couch": { t: "svg", n: 1 },
  "st-dead-bug-post": { t: "webp", n: 1 },
  "st-doorway-pec": { t: "svg", n: 1 },
  "st-glute-bridge": { t: "webp", n: 2 },
  "st-hamstring": { t: "webp", n: 2 },
  "st-kneeling-hipflexor": { t: "webp", n: 2 },
  "st-levator": { t: "svg", n: 1 },
  "st-pec-minor": { t: "svg", n: 1 },
  "st-thoracic-ext": { t: "svg", n: 1 },
  "st-upper-trap": { t: "webp", n: 2 },
  "st-wall-angel": { t: "svg", n: 2 },
  "stiff-leg-deadlift": { t: "webp", n: 2 },
  "straight-arm-pulldown": { t: "webp", n: 2 },
  "svend-press": { t: "webp", n: 2 },
  "t-bar-row": { t: "webp", n: 2 },
  "tricep-pushdown": { t: "webp", n: 2 },
  "upright-row": { t: "webp", n: 2 },
  "woodchopper": { t: "webp", n: 2 },
  "wrist-curl": { t: "webp", n: 2 },
};
